# Generated by Django 4.2.7 on 2023-11-24 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='creation_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 24, 11, 42, 21, 662309, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 11, 24, 11, 42, 21, 662309, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата рождения'),
        ),
    ]
